Introduction to Tensors

In [ ]:
import tensorflow as tf

print(tf.__version__)

2.8.2


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[7, 10],
                     [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Creating another matrix with different shape and data type
another_matrix = tf.constant([[1.0, 2.0],
                              [3.0, 4.0],
                              [5.0, 6.0]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
my_tensor = tf.constant([
                         [
                          [1, 2, 3, 4],
                          [3, 4, 5, 6],
                          [5, 6, 7, 8]
                         ],
                         [
                          [7, 8, 9, 10],
                          [9, 10, 11, 12],
                          [11, 12, 13, 14]
                         ],
                        ])
my_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  6],
        [ 5,  6,  7,  8]],

       [[ 7,  8,  9, 10],
        [ 9, 10, 11, 12],
        [11, 12, 13, 14]]], dtype=int32)>

In [ ]:
my_tensor.ndim

3

In [ ]:
# 4 dimensional tensor
big_tensor = tf.constant([
                          [
                           [
                            [1, 2, 3, 4, 5],
                            [6, 7, 8, 9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20]
                           ],
                           [
                            [1, 2, 3, 4, 5],
                            [6, 7, 8, 9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20]
                           ],
                           [
                            [1, 2, 3, 4, 5],
                            [6, 7, 8, 9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20]
                           ]
                          ],
                          [
                           [
                            [1, 2, 3, 4, 5],
                            [6, 7, 8, 9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20]
                           ],
                           [
                            [1, 2, 3, 4, 5],
                            [6, 7, 8, 9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20]
                           ],
                           [
                            [1, 2, 3, 4, 5],
                            [6, 7, 8, 9, 10],
                            [11, 12, 13, 14, 15],
                            [16, 17, 18, 19, 20]
                           ]
                          ]
                        ])

big_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]], dtype=int32)>

In [ ]:
big_tensor.ndim

4

In [ ]:
# simple 5 dimensional tensor
simple_tensor = tf.constant([[[[[5]]]]])
simple_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 1), dtype=int32, numpy=array([[[[[5]]]]], dtype=int32)>

In [ ]:
simple_tensor.ndim

5

In [ ]:
# Changable tensor
changable_tensor = tf.Variable([2, 3])
unchangable_tensor = tf.constant([3, 4])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [ ]:
# Assign different value to variable
changable_tensor[0].assign(7)
changable_tensor[1].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Create random uniform tensor
random_tensor1 = tf.random.uniform(shape=[2,3,4], minval = 0, maxval = 10, dtype = tf.float16)
random_tensor1

<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
array([[[7.99 , 4.836, 4.902, 7.312],
        [1.533, 7.793, 2.695, 9.68 ],
        [9.21 , 2.12 , 9.29 , 8.78 ]],

       [[5.254, 9.39 , 3.564, 6.4  ],
        [1.826, 9.26 , 9.23 , 9.54 ],
        [1.387, 7.453, 3.78 , 5.684]]], dtype=float16)>

In [ ]:
from tensorflow._api.v2 import random
# Create random normal tensor
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.normal(shape=(2,3,4), dtype = tf.float16)
random_tensor3 = tf.random.Generator.from_seed(42)
random_tensor3 = random_tensor3.normal(shape=(2,3,4), dtype = tf.float16)

random_tensor2, random_tensor3, random_tensor2 == random_tensor3

(<tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
 array([[[-0.7563 , -0.06854,  0.0759 , -1.258  ],
         [-0.2319 , -1.811  ,  0.0999 , -0.51   ],
         [-0.7534 , -0.572  ,  0.1481 , -0.2336 ]],
 
        [[-0.3523 ,  0.4062 , -1.053  ,  1.205  ],
         [ 1.6875 , -0.4463 , -2.342  ,  0.99   ],
         [-0.08765, -0.6357 , -0.616  , -1.944  ]]], dtype=float16)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float16, numpy=
 array([[[-0.7563 , -0.06854,  0.0759 , -1.258  ],
         [-0.2319 , -1.811  ,  0.0999 , -0.51   ],
         [-0.7534 , -0.572  ,  0.1481 , -0.2336 ]],
 
        [[-0.3523 ,  0.4062 , -1.053  ,  1.205  ],
         [ 1.6875 , -0.4463 , -2.342  ,  0.99   ],
         [-0.08765, -0.6357 , -0.616  , -1.944  ]]], dtype=float16)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=bool, numpy=
 array([[[ True,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]],
 
        [[ True,  True,  True,  True],
         [ True,  True,  True,  

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([
                            [1, 2],
                            [3, 4],
                            [5, 6]
                           ])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# Create tensor of all 1
tf.ones([3, 4], tf.int8)

<tf.Tensor: shape=(3, 4), dtype=int8, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)>

In [ ]:
# Create tensor of all 0
tf.zeros([3, 4], tf.int8)

<tf.Tensor: shape=(3, 4), dtype=int8, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)>

In [ ]:
# Create a NumPy array
import numpy as np
change_numpy = np.array([1, 2, 3], dtype=np.int8)
change_numpy

array([1, 2, 3], dtype=int8)

In [ ]:
# Changing NumPy arrays into tensors (tensors are faster as it runs on GPU)
# Below will not work because it has 3 elements, but shape(2, 3, 4) has 24 elements
# changed_numpy = tf.constant(change_numpy, dtype = tf.int8, shape = (2, 3, 4))
# Lets create new numpy array with 24 elements
change_numpy = np.arange(1, 25, dtype=int)
change_numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Changing NumPy arrays into tensors (tensors are faster as it runs on GPU)
changed_numpy = tf.constant(change_numpy, dtype = tf.int8, shape = (2, 3, 4))
changed_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int8, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int8)>

In [ ]:
# Create a "rank 4" tensor (rank = ndim)
#rank_4_tensor = tf.zeros(dtype = tf.int8, shape = (2, 3, 4, 5))
rank_4_tensor = tf.random.Generator.from_seed(42)
rank_4_tensor = rank_4_tensor.normal(shape=(2,3,4,5), dtype = tf.float16)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float16, numpy=
array([[[[-0.7563 , -0.06854,  0.0759 , -1.258  , -0.2319 ],
         [-1.811  ,  0.0999 , -0.51   , -0.7534 , -0.572  ],
         [ 0.1481 , -0.2336 , -0.3523 ,  0.4062 , -1.053  ],
         [ 1.205  ,  1.6875 , -0.4463 , -2.342  ,  0.99   ]],

        [[-0.08765, -0.6357 , -0.616  , -1.944  , -0.483  ],
         [-0.5244 , -1.034  ,  1.307  , -1.519  , -0.4585 ],
         [ 0.5713 , -1.533  ,  0.4534 ,  1.148  , -1.266  ],
         [-0.4746 ,  2.006  ,  0.283  , -0.303  , -1.443  ]],

        [[ 1.004  ,  0.2086 ,  0.357  ,  1.064  ,  1.243  ],
         [-2.217  ,  0.187  ,  0.6616 ,  0.0138 , -0.2483 ],
         [ 1.211  , -0.7197 , -0.04083,  2.68   ,  1.092  ],
         [ 0.3315 , -0.6797 ,  0.4473 , -0.1781 ,  0.2488 ]]],


       [[[ 0.4968 ,  0.826  ,  1.034  , -0.2491 , -1.578  ],
         [-0.9214 ,  0.2686 ,  0.942  , -0.947  , -0.711  ],
         [ 1.3    , -0.6147 , -1.472  , -0.1009 ,  0.9604 ],
         [-1.637  ,  0.

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float16, numpy=
array([[[-0.7563 , -0.06854,  0.0759 , -1.258  , -0.2319 ],
        [-1.811  ,  0.0999 , -0.51   , -0.7534 , -0.572  ],
        [ 0.1481 , -0.2336 , -0.3523 ,  0.4062 , -1.053  ],
        [ 1.205  ,  1.6875 , -0.4463 , -2.342  ,  0.99   ]],

       [[-0.08765, -0.6357 , -0.616  , -1.944  , -0.483  ],
        [-0.5244 , -1.034  ,  1.307  , -1.519  , -0.4585 ],
        [ 0.5713 , -1.533  ,  0.4534 ,  1.148  , -1.266  ],
        [-0.4746 ,  2.006  ,  0.283  , -0.303  , -1.443  ]],

       [[ 1.004  ,  0.2086 ,  0.357  ,  1.064  ,  1.243  ],
        [-2.217  ,  0.187  ,  0.6616 ,  0.0138 , -0.2483 ],
        [ 1.211  , -0.7197 , -0.04083,  2.68   ,  1.092  ],
        [ 0.3315 , -0.6797 ,  0.4473 , -0.1781 ,  0.2488 ]]],
      dtype=float16)>

In [ ]:
# Get shape, dimension and size of the tensor
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get all attributes of a tensor
print("Datatype:", rank_4_tensor.dtype)
print("Number of dimensions/rank:", rank_4_tensor.ndim)
print("Shape:", rank_4_tensor.shape)
print("Number of elements on 0 axis:", rank_4_tensor.shape[0])
print("Number of elements on last axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Datatype: <dtype: 'float16'>
Number of dimensions/rank: 4
Shape: (2, 3, 4, 5)
Number of elements on 0 axis: 2
Number of elements on last axis: 5
Total number of elements: 120


In [ ]:
# Get first 2 elements of some list
list_sample = [1, 2, 3, 4]
list_sample[:2]

[1, 2]

In [ ]:
# Get first 2 elements of all dimension of the tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float16, numpy=
array([[[[-0.7563 , -0.06854],
         [-1.811  ,  0.0999 ]],

        [[-0.08765, -0.6357 ],
         [-0.5244 , -1.034  ]]],


       [[[ 0.4968 ,  0.826  ],
         [-0.9214 ,  0.2686 ]],

        [[-2.525  ,  0.0508 ],
         [ 1.321  ,  0.346  ]]]], dtype=float16)>

In [ ]:
# New rank 2 tensor
rank_2_tensor = tf.random.Generator.from_seed(2)
rank_2_tensor = rank_2_tensor.normal(shape=(2,3), dtype = tf.float16)
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[-0.10126, -0.2744 ,  1.421  ],
       [ 1.261  , -0.4365 , -1.964  ]], dtype=float16)>

In [ ]:
# Add 1 extra dimension to rank_2_tensor
# ... means all the dimensions before
rank_2_tensor[..., tf.newaxis]

<tf.Tensor: shape=(2, 3, 1), dtype=float16, numpy=
array([[[-0.10126],
        [-0.2744 ],
        [ 1.421  ]],

       [[ 1.261  ],
        [-0.4365 ],
        [-1.964  ]]], dtype=float16)>

In [ ]:
# Another way to add a new axis
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 3, 1), dtype=float16, numpy=
array([[[-0.10126],
        [-0.2744 ],
        [ 1.421  ]],

       [[ 1.261  ],
        [-0.4365 ],
        [-1.964  ]]], dtype=float16)>

In [ ]:
# Expand 0-axis
tf.expand_dims(rank_2_tensor, axis = 0)

<tf.Tensor: shape=(1, 2, 3), dtype=float16, numpy=
array([[[-0.10126, -0.2744 ,  1.421  ],
        [ 1.261  , -0.4365 , -1.964  ]]], dtype=float16)>

Tensor Manipulation (operations)

In [ ]:
# Addition
tensor_manipulation = tf.constant([[1, 2],
                                   [3, 4]])
tensor_manipulation + 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

In [ ]:
# Multiplication
tensor_manipulation * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Subtraction
tensor_manipulation - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

In [ ]:
# Same multiplication but with a function
# This way it'll use the GPU and will be faster
tf.multiply(tensor_manipulation, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

Matrix multiplication

In [ ]:
# Create 2 tensors to multiply
matmul_tensor_1 = tf.constant([[1, 2, 5],
                               [7, 2, 1],
                               [3, 3, 3]])

matmul_tensor_2 = tf.constant([[3, 5],
                               [6, 7],
                               [1, 8]])

tf.matmul(matmul_tensor_1, matmul_tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Another way of matrix multiply
matmul_tensor_1 @ matmul_tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Another way of matrix multiply
tf.tensordot(matmul_tensor_1, matmul_tensor_2, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Create tensor to test Reshape
shape_tester = tf.constant([[1, 2],
                            [4, 5],
                            [7, 8]])
shape_tester

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)>

In [ ]:
# Reshape tensor
tf.reshape(shape_tester, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [5, 7, 8]], dtype=int32)>

In [ ]:
# We can do the same with transpose but it will yeild different result
tf.transpose(shape_tester)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [ ]:
# Here's the difference
shape_tester, tf.reshape(shape_tester, shape=(2, 3)), tf.transpose(shape_tester)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 5],
        [7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [5, 7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 4, 7],
        [2, 5, 8]], dtype=int32)>)

In [ ]:
# Changing datatype
# First create a tensor with default datatype (float32)
datatype_tester = tf.constant([[1., 2., 3.],
                               [4., 5., 6.],
                               [7., 8., 9.]])
datatype_tester

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [ ]:
# Change float32 to float16 (reducing precision)
datatype_tester = tf.cast(datatype_tester, dtype = tf.float16)
datatype_tester

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [ ]:
# Change float32 to int16
datatype_tester = tf.cast(datatype_tester, dtype = tf.int16)
datatype_tester

<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)>

Tensor aggregation

In [ ]:
# Get absolute values
abs_tester = tf.constant([-7, 7, 11, -11])
abs_tester, tf.abs(abs_tester)

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ -7,   7,  11, -11], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  7, 11, 11], dtype=int32)>)

In [ ]:
# Create aggreate tester
aggregate_tester = [3., 4., 5.]

In [ ]:
# Get maximum
tf.reduce_max(aggregate_tester)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [ ]:
# Get minimum
tf.reduce_min(aggregate_tester)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
# Get mean
tf.reduce_mean(aggregate_tester)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
# Get sum
tf.reduce_sum(aggregate_tester)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [ ]:
# Get variance
tf.math.reduce_variance(aggregate_tester)

<tf.Tensor: shape=(), dtype=float32, numpy=0.6666667>

In [ ]:
# Get STD
tf.math.reduce_std(aggregate_tester)

<tf.Tensor: shape=(), dtype=float32, numpy=0.8164966>

In [ ]:
# Get the index of maximum value
tf.math.argmax(aggregate_tester)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Get the index of minimum value
tf.math.argmin(aggregate_tester)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Squeezing tensor - deleting dimensions that doesn't have any elements
tf.random.set_seed(42)
squeeze_tester = tf.constant(tf.random.uniform(shape = [50]), shape = [1, 1, 1, 1, 50])
squeeze_tester, squeeze_tester.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>, TensorShape([1, 1, 1, 1, 50]))

In [ ]:
tensor_squeezed = tf.squeeze(squeeze_tester)
tensor_squeezed, tensor_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

One-hot encoding tensors

In [ ]:
# Create list of indicies
some_list = [0, 1, 2, 3] # red, green, blue, purple
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Create custom values for one-hot encoding
tf.one_hot(some_list, depth = 4, on_value = "yey", off_value="ney")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yey', b'ney', b'ney', b'ney'],
       [b'ney', b'yey', b'ney', b'ney'],
       [b'ney', b'ney', b'yey', b'ney'],
       [b'ney', b'ney', b'ney', b'yey']], dtype=object)>

Math Operations

In [ ]:
# Create tensor
math_tester = tf.range(1, 10)
math_tester

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square tensor
tf.square(math_tester)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Log tensor
tf.math.log(tf.cast(math_tester, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [ ]:
# SQRT tensor
tf.sqrt(tf.cast(math_tester, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

Tensor and NumPy

In [ ]:
# Create tensor from a NumPy
numpy_tensor = tf.constant(np.array([1., 2., 3.]))
numpy_tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
# Create NumPy from tensor
np.array(numpy_tensor), type(np.array(numpy_tensor))

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
# Another way of converting tensor to NumPy
numpy_tensor.numpy(), type(numpy_tensor.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
# Default type of a tensor created directly and a tensor created from numpy will be slightly different
tensor_type_orig = tf.constant([1., 2., 3.])
tensor_type_numpy = tf.constant(np.array([1., 2., 3.]))
tensor_type_orig.dtype, tensor_type_numpy.dtype

(tf.float32, tf.float64)